name: Auto commit

on:
  push:
    branches:
      - workflow
  schedule:
    - cron: "0 0 * * 0,1,3,4,6"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --local user.email "87859520+Parixshit@users.noreply.github.com"
          git config --local user.name "Parixshit"

      - name: Generate commits
        run: |
          num_commits=$(( RANDOM % 30 + 1 ))
          for i in $(seq $num_commits); do
            commit_message="feat: auto commit $i of $num_commits"
            echo -e "**_Commit date: $(date +"%a, %d %b %Y %T")_**" > README.md
            git add README.md
            git commit -m "$commit_message"
            sleep 1
          done

      - name: Push changes
        run: git push origin main
