name: Auto Commit

on:
  schedule:
    # This workflow runs at 00:00 (UTC) / 05:30 AM (IST) every day, except for Tuesdays and Fridays.
    - cron: "0 0 * * 0,1,3,4,6"
  workflow_dispatch:
    inputs:
      num_commits:
        description: "Number of commits"
        required: true
      repository:
        description: "Repo to check out (e.g. owner/repo)"
        required: true
      branch:
        description: "Branch to push changes to"
        required: true

env:
  REPOSITORY: ${{ inputs.repository || 'Parixshit/Green' }}
  BRANCH: ${{ inputs.branch || 'main' }}

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check Repository
        run: |
          if ! git ls-remote "https://${{ secrets.PAT }}@github.com/${{ env.REPOSITORY }}" &> /dev/null; then
            echo "Repository not found"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.PAT }}
          ref: ${{ env.BRANCH }}

      - name: Configure Git
        run: |
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Download Emojis
        run: |
          curl -s "https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json" | jq -r '.gitmojis[].code' > emojis.txt

      - name: Generate Commits
        run: |
          total_commits=${{ inputs.num_commits }}
          if [ -z "$total_commits" ]; then
            total_commits=$(shuf -i 1-30 -n 1)
          fi
          for commit_number in $(seq $total_commits); do
            if [ $total_commits -gt 30 ]; then
              commit_date=$(TZ="Asia/Kolkata" date -d "$(shuf -i 1-365 -n 1) days ago" +"%a, %d %b %Y %r")
            else
              commit_date=$(TZ="Asia/Kolkata" date +"%a, %d %b %Y %r")
            fi
            random_emoji=$(shuf -n 1 emojis.txt)
            commit_message="$random_emoji Commit $commit_number on $commit_date"
            sed -i "1s|.*|**${{ github.actor }} Committed on: $commit_date** <!-- $(uuidgen) -->|" README.md
            git add README.md
            git commit --date="$commit_date" -s -m "$commit_message"
          done

      - name: Push Changes
        run: git push -u origin ${{ github.head_ref }}
