name: Auto commit

on:
  schedule:
    - cron: "0 0 * * 0,1,3,4,6"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --local user.email "87859520+Parixshit@users.noreply.github.com"
          git config --local user.name "Parixshit"

      - name: Generate commits
        run: |
          for i in $(seq $(( RANDOM % 30 + 1 ))); do
            commit_message="feat: auto commit"
            sed -i "1s/.*/**$GITHUB_ACTOR Committed on: $(date +"%a, %d %b %Y %T")**/" README.md
            git add README.md
            git commit -m "$commit_message"
            sleep 1
          done

      - name: Push changes
        run: git push origin main
